// Mocks generated by Mockito 5.0.7 from annotations
// in tabibi/test/features/authantication/presentation/cubit/auth_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tabibi/core/error/failures.dart' as _i7;
import 'package:tabibi/features/authentication/domain/entities/user.dart'
    as _i4;
import 'package:tabibi/features/authentication/domain/usecases/login.dart'
    as _i5;
import 'package:tabibi/features/authentication/domain/usecases/logout.dart'
    as _i3;
import 'package:tabibi/features/authentication/domain/usecases/signin.dart'
    as _i8;
    import 'package:tabibi/features/authentication/domain/usecases/auto_login.dart'
    as _i9;


// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [Logout].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogout extends _i1.Mock implements _i3.Logout {
  MockLogout() {
    _i1.throwOnMissingStub(this);
  }

}
class MockAutoLogin extends _i1.Mock implements _i9.AutoLogin {
  MockAutoLogin() {
    _i1.throwOnMissingStub(this);
  }

}

/// A class which mocks [Login].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogin extends _i1.Mock implements _i5.Login {
  MockLogin() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i4.User>> call(
          String? username, String? password) =>
      (super.noSuchMethod(Invocation.method(#call, [username, password]),
              returnValue: Future<_i2.Either<_i7.Failure, _i4.User>>.value(
                  _FakeEither<_i7.Failure, _i4.User>()))
          as _i6.Future<_i2.Either<_i7.Failure, _i4.User>>);
}

/// A class which mocks [Signin].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignin extends _i1.Mock implements _i8.Signin {
  MockSignin() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i4.User>> call(
          String? username, String? password) =>
      (super.noSuchMethod(Invocation.method(#call, [username, password]),
              returnValue: Future<_i2.Either<_i7.Failure, _i4.User>>.value(
                  _FakeEither<_i7.Failure, _i4.User>()))
          as _i6.Future<_i2.Either<_i7.Failure, _i4.User>>);
}
