// Mocks generated by Mockito 5.0.7 from annotations
// in tabibi/test/features/consultations/presentation/cubit/consultation_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tabibi/core/error/failures.dart' as _i5;
import 'package:tabibi/features/consultations/domain/entities/consultation.dart'
    as _i6;
import 'package:tabibi/features/consultations/domain/usecasese/add_cons.dart'
    as _i8;
import 'package:tabibi/features/consultations/domain/usecasese/get_cons.dart'
    as _i3;
import 'package:tabibi/features/consultations/domain/usecasese/get_cons_bySpeci.dart'
    as _i9;
import 'package:tabibi/features/consultations/domain/usecasese/get_my_cons.dart'
    as _i7;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [GetCons].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCons extends _i1.Mock implements _i3.GetCons {
  MockGetCons() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Consultation>>> call() =>
      (super.noSuchMethod(Invocation.method(#call, []),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i6.Consultation>>>.value(
                      _FakeEither<_i5.Failure, List<_i6.Consultation>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Consultation>>>);
}

/// A class which mocks [GetMyCons].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMyCons extends _i1.Mock implements _i7.GetMyCons {
  MockGetMyCons() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Consultation>>> call(
          String? userId) =>
      (super.noSuchMethod(Invocation.method(#call, [userId]),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i6.Consultation>>>.value(
                      _FakeEither<_i5.Failure, List<_i6.Consultation>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Consultation>>>);
}

/// A class which mocks [AddCons].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddCons extends _i1.Mock implements _i8.AddCons {
  MockAddCons() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> call(_i6.Consultation? consultation) =>
      (super.noSuchMethod(Invocation.method(#call, [consultation]),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}

/// A class which mocks [GetConsBySpeci].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetConsBySpeci extends _i1.Mock implements _i9.GetConsBySpeci {
  MockGetConsBySpeci() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Consultation>>> call(
          String? specialization) =>
      (super.noSuchMethod(Invocation.method(#call, [specialization]),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i6.Consultation>>>.value(
                      _FakeEither<_i5.Failure, List<_i6.Consultation>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Consultation>>>);
}
