// Mocks generated by Mockito 5.0.7 from annotations
// in tabibi/test/features/authantication/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tabibi/core/network/internet_info.dart' as _i3;
import 'package:tabibi/features/authentication/data/data%20sources/auth_remote_data_source.dart'
    as _i5;
import 'package:tabibi/features/authentication/domain/entities/user.dart'
    as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeUser extends _i1.Fake implements _i2.User {}

/// A class which mocks [InternetInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternetInfo extends _i1.Mock implements _i3.InternetInfo {
  MockInternetInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnect =>
      (super.noSuchMethod(Invocation.getter(#isConnect),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i5.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.User> signinUser(String? username, String? password) =>
      (super.noSuchMethod(Invocation.method(#signinUser, [username, password]),
              returnValue: Future<_i2.User>.value(_FakeUser()))
          as _i4.Future<_i2.User>);
  @override
  _i4.Future<_i2.User> loginUser(String? username, String? password) =>
      (super.noSuchMethod(Invocation.method(#loginUser, [username, password]),
              returnValue: Future<_i2.User>.value(_FakeUser()))
          as _i4.Future<_i2.User>);
}
